'use client';
import { useState } from 'react';
import './globals.scss';
import CustomCursor from '@/components/Cursor';
import CursorProvider from '@/components/Cursor/CursorProvider';
import Socials from '@/components/socials';


import { Inter, Space_Grotesk } from 'next/font/google';
import Footer from '@/components/Footer';
import Header from '@/components/Navigation/Header';

const inter = Inter({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

const space_grotesk = Space_Grotesk({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

/* export const metadata: Metadata = {
  title: 'Future vision',
  description: 'Generated by create next app',
};
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [active, setActive] = useState(false);
  return (
    <html lang='en'>
      {/* className={`${inter.className} ${space_grotesk.className}`} */}
      <body >
        <CursorProvider>
          <CustomCursor />
         <Header />
         
          <Socials />
          {children}
        </CursorProvider>
      <Footer />
      </body>
    </html>
  );
}
